---1---
SELECT UNIQUE(LAUNCH_SITE)
FROM SpaceX;

---2---
SELECT DATE,LAUNCH_SITE
FROM SpaceX
WHERE LAUNCH_SITE
LIKE '%CCA%'
ORDER BY DATE
ASC;

---3---
SELECT BOOSTER_VERSION, SUM(PAYLOAD_MASS__KG_)
FROM (SELECT * FROM SpaceX WHERE CUSTOMER LIKE '%NASA%')
GROUP BY BOOSTER_VERSION
ORDER BY SUM(PAYLOAD_MASS__KG_)
DESC;


---4---
SELECT AVG(PAYLOAD_MASS__KG_)
FROM (SELECT BOOSTER_VERSION, PAYLOAD_MASS__KG_ FROM SpaceX WHERE BOOSTER_VERSION LIKE '%F9 v1.1%');


---5---
SELECT MIN(DATE)
FROM (SELECT DATE, LANDING__OUTCOME FROM SpaceX)
WHERE LANDING__OUTCOME
LIKE '%ground pad%';

---6---
SELECT BOOSTER_VERSION, LANDING__OUTCOME, PAYLOAD_MASS__KG_
FROM (SELECT BOOSTER_VERSION, LANDING__OUTCOME, PAYLOAD_MASS__KG_ FROM SpaceX WHERE LANDING__OUTCOME = 'Success (drone ship)')
WHERE (PAYLOAD_MASS__KG_ >= 4000) AND (PAYLOAD_MASS__KG_ <= 6000);


---7---
SELECT LANDING__OUTCOME, COUNT(LANDING__OUTCOME)
FROM SpaceX
GROUP BY LANDING__OUTCOME
ORDER BY COUNT(LANDING__OUTCOME)
DESC;


---8---
SELECT BOOSTER_VERSION, SUM(PAYLOAD_MASS__KG_)
FROM SpaceX
GROUP BY BOOSTER_VERSION
ORDER BY SUM(PAYLOAD_MASS__KG_)
DESC;

---9---
SELECT DATE, LANDING__OUTCOME, BOOSTER_VERSION, LAUNCH_SITE
FROM (SELECT LANDING__OUTCOME, BOOSTER_VERSION, LAUNCH_SITE, DATE FROM SpaceX WHERE LANDING__OUTCOME LIKE '%Fail%')
WHERE DATE
LIKE '%2015%';

---10---
SELECT LANDING__OUTCOME, COUNT(LANDING__OUTCOME)
FROM (SELECT DATE, LANDING__OUTCOME FROM SpaceX WHERE (DATE >= '20100604') AND (DATE <= '20170320'))
GROUP BY LANDING__OUTCOME
ORDER BY COUNT(LANDING__OUTCOME)
DESC;